//errors.js

try {
    console.log(great);
} catch (error) {
    console.log(error.message);
}